### ISSUE TITLE
webmanifest support

### ISSUE THREAD

**Issue by ThaUnknown** [gluon-framework/gluon#14]
Supporting [webmanifest](https://developer.mozilla.org/en-US/docs/Web/Manifest) could be cool, this would allow for stuff like custom titlebar colors, icons, shortcuts etc, I can see 2 ways of implementing this:

1. suffer and implement each feature by hand
2. register the site as an app: going to the options burger, more tools, create shortcut and setting it as a window creates the site as a ""standalone app"" which registers an app ID, then the browser simply launches it with --app-id ex: `chrome_proxy.exe  --profile-directory=Default --app-id=cinhimbnkkaeohfgghhklpknlkffjgod`, this would automatically support all webmanifest features, even ones enabled experimentally with flags and fix stuff like #12

**Comment by CanadaHonk** [comment]
Have you checked if this already works? Unsure if launching a site with --app would use it or if it's installed only.

**Comment by ThaUnknown** [comment]
@CanadaHonk yes this works, but it's INSANELY specific
[assumption] the app-id is a hash of: site URL, profile name and profile location 
this worked when I did this for startBrowser:
```js
export default async ({ browserName, browserPath, dataPath }, { url, windowSize }) => {
  return await StartBrowser(browserPath, [
    `--app-id=mjoklplbddabcmpepnokjaffbmgbkkgg`,
    `--remote-debugging-pipe`,
    windowSize ? `--window-size=${windowSize.join(',')}` : '',
    ...`--new-window --disable-extensions --disable-default-apps --disable-breakpad --disable-crashpad --disable-background-networking --disable-domain-reliability --disable-component-update --disable-sync --disable-features=AutofillServerCommunication ${presets.perf}`.split(' ')
  ], 'stdio', { browserName });
};
```
I had to remove `--profile-directory=Default` and the `dataPath` option for it to work.
End result:
![image](https://user-images.githubusercontent.com/6506529/210192316-e86737a0-24f5-486a-88ff-d4c26582ec2b.png)
Respecting webmanifest it has a custom title bar color and the chrome controls, sick!
Here's what I did [brave]
For github: 
![image](https://user-images.githubusercontent.com/6506529/210192243-654dc10f-60c0-4f97-88e1-da20980c6abd.png)
make sure to check Open as window
![image](https://user-images.githubusercontent.com/6506529/210192254-acbab463-3694-4c69-9bd8-f91393f0981b.png)
went to desktop and got app id from the launch parameters
`"C:\Program Files\BraveSoftware\Brave-Browser\Application\chrome_proxy.exe"  --profile-directory=Default --app-id=mjoklplbddabcmpepnokjaffbmgbkkgg`
this doesn't actually have to be chrome_proxy, it can just be chrome.exe [brave.exe in this case]

So I assume for this work gluton would need so somehow create an app like the shortcut thing did, and launch it from the same path and profile that created the app, no clue exactly how to do this, but it's 100% possible and decreases the workload of managing these features by a mile, especially stuff like custom title bars across different operating systems which frameworks like tauri struggle with a LOT

**Comment by CanadaHonk** [comment]
I meant already possible i.e. --app already handles webmanifest/PWA features without requiring an --app-id or install haha, but good info nevertheless.

**Comment by ThaUnknown** [comment]
> I meant already possible i.e. --app already handles webmanifest/PWA features without requiring an --app-id or install haha, but good info nevertheless.

yes but app-id install enables PWA features, --app doesn't, it only does some webmanifest things, but not all

**Comment by ThaUnknown** [comment]
notable issue: installable PWAs sometimes get unregistered across updates so the app-id would likely need to be re-registered after each startup

this also doesn't solve the issue of API's such as FileHandlingAPI and WebShareTargetAPI, as either: A the file handle won't be forwarded to the browser via the [launchQueue](https://developer.chrome.com/en/articles/file-handling/#feature-detection) or the node wrapper won't launch alongside the app, hmmm

**Comment by ThaUnknown** [comment]
documenting: https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/windows_pwa_integration.md#file-handling-support

**Comment by CanadaHonk** [comment]
Closing as Firefox has no support, so would introduce major compatibility issues. Possible to revisit in future if/when isolated web apps become more of a standard.
