### ISSUE TITLE
Instructions from README don't work on my mac m1 with chrome installed

### ISSUE THREAD

**Issue by borkdude** [gluon-framework/gluon#30]
Full output:

borkdude@m1 /tmp $ git clone https://github.com/gluon-framework/examples.git
Cloning into 'examples'...
remote: Enumerating objects: 48, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 48 (delta 12), reused 44 (delta 11), pack-reused 0
Receiving objects: 100% (48/48), 260.47 KiB | 1.65 MiB/s, done.
Resolving deltas: 100% (12/12), done.
borkdude@m1 /tmp $ cd examples
borkdude@m1 /tmp/examples (main) $ cd gluworld
borkdude@m1 /tmp/examples/gluworld (main) $ npm install

added 2 packages, and audited 3 packages in 4s

found 0 vulnerabilities
borkdude@m1 /tmp/examples/gluworld (main) $ cat package.json
{"type":"module","dependencies":{"@gluon-framework/gluon":"^0.9.0"}}%
borkdude@m1 /tmp/examples/gluworld (main) $ node .
[Gluon] starting browser...
[Gluon] checking if chrome exists: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome true
[Gluon] browser path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[Gluon] data path: /private/tmp/examples/gluworld/node_modules/@gluon-framework/gluon/chrome_data
[Gluon] connecting to CDP over stdio pipe...
[Gluon] browser: Chrome/108.0.5359.124
file:///private/tmp/examples/gluworld/node_modules/@gluon-framework/gluon/src/launcher/inject.js:22
      targetId: target.targetId,
                       ^

TypeError: Cannot read properties of undefined (reading 'targetId')
    at default (file:///private/tmp/examples/gluworld/node_modules/@gluon-framework/gluon/src/launcher/inject.js:22:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async default (file:///private/tmp/examples/gluworld/node_modules/@gluon-framework/gluon/src/launcher/start.js:36:10)
    at async default (file:///private/tmp/examples/gluworld/node_modules/@gluon-framework/gluon/src/browser/chromium.js:11:10)
    at async startBrowser (file:///private/tmp/examples/gluworld/node_modules/@gluon-framework/gluon/src/index.js:113:18)
    at async Module.open (file:///private/tmp/examples/gluworld/node_modules/@gluon-framework/gluon/src/index.js:131:19)
    at async file:///private/tmp/examples/gluworld/index.js:38:19

Node.js v17.8.0

**Comment by borkdude** [comment]
I added the loggin and then it started working :)

```
[Gluon] browser: Chrome/108.0.5359.124
=> {
  targetInfos: [
    {
      targetId: '06306E365AD311C0C37C1A870A2D539E',
      type: 'page',
      title: '',
      url: 'file:///private/tmp/examples/gluworld/index.html',
      attached: false,
      canAccessOpener: false,
      browserContextId: '0998ACD215F318856D831E876C29C351'
    }
  ]
}
```

**Comment by CanadaHonk** [comment]
Oh nice, might be a tiny timing issue, will look into it. Thanks for the report!
