### ISSUE TITLE
Affiliation with the Gluon App?

### ISSUE THREAD

**Issue by vincentritter** [gluon-framework/gluon#42]
Hey there,

Just wondering if Gluon has any affiliation with [Gluon for Micro.blog](https://gluon.app)? It's been around for some time.

If not, perhaps you can make it clear it's not affiliated? Was a little confused at first.

Open to suggestions.

– Vincent

**Comment by CanadaHonk** [comment]
Nope, Gluon has no affiliation to any other projects. There are many other things named Gluon and can't really clear them all up haha. (And a bit too late to change the name now.)
