### ISSUE TITLE
Print API

### ISSUE THREAD

**Issue by tmblog** [gluon-framework/gluon#44]
Is there any way to print silently bypassing the OS prompt? Electron and NWJS have it. It would be a great addition and surpass Tauri and Neutralinojs.
:-)
Looks great BTW.

**Comment by CanadaHonk** [comment]
Like preventing cmd opening? Will look into.

**Comment by tmblog** [comment]
Thanks, here's the NWJS docs on it https://docs.nwjs.io/en/latest/References/Window/#winprintoptions
`autoprint {Boolean} whether to print without the need for user’s interaction; optional, true by default`

**Comment by CanadaHonk** [comment]
Will make the issue/plan into a more generic print API.

**Comment by CanadaHonk** [comment]
Might make it a new optional "plugin"-style dependency like [`@gluon-framework/widevine`](https://github.com/gluon-framework/widevine) to avoid adding a few dependencies most won't need, will get some opinions [from the Discord](https://discord.gg/RFtUCA8fST).

**Comment by tmblog** [comment]
Will be great, either way and thank you! In terms of popularity try searching "Tauri Silent print", "Electron silent print", "NWJS silent print", "neutralino silent print", "js silent print", etc. There's a decent demand IMO. This might win you over a fair few users.
But willl leave that to you, Thanks again!

**Comment by CanadaHonk** [comment]
Don't mind how many users, as long as I make one person happy I'm down to implement it haha, thanks for the request. Might be in next release (0.13) depending on difficulty.

**Comment by tmblog** [comment]
Looking forward to it already! Have a good one whatever it's you're doing. Thanks again.

**Comment by CanadaHonk** [comment]
Going to implement an API for allowing printing/saving to a PDF, which then allows you to use a library like [pdf-to-printer](https://github.com/artiebits/pdf-to-printer) or [unix-print](https://github.com/artiebits/unix-print) to print with a printer yourself to avoid having to deal with platform-specific features and added dependencies.

**Comment by CanadaHonk** [comment]
`Window.page.printToPDF` has been added! Typedef is already updated for how to use, and docs will be added soon.

**Comment by tmblog** [comment]
Thank you so much! Where can I find the typedef can't wait to try it.

**Comment by CanadaHonk** [comment]
https://github.com/gluon-framework/gluon/blob/main/gluon.d.ts#L190-L209
