### ISSUE TITLE
Node14: SyntaxError: Unexpected token '??='

### ISSUE THREAD

**Issue by Rabbitzzc** [gluon-framework/gluon#47]
Env: Local

Need Update Node.js to version 16+

https://github.com/gluon-framework/gluon/blob/main/src/api/v8Cache.js#L25
Or update code to
```ts
    urls ??= await getScriptUrls(includePreload);
    // urls = urls ?? await getScriptUrls(includePreload);
```

**Comment by CanadaHonk** [comment]
Gluon does/will not support Node <16, as stated in docs: https://gluonjs.org/docs/guide/quick-start/#requirements
