### ISSUE TITLE
RFC: Restrict Window navigation

### ISSUE THREAD

**Issue by CanadaHonk** [gluon-framework/gluon#51]
Window/top-level navigations should be restricted by default. This will be handled by the `allowRedirects` Window option, with the values:
- `false`: **No** redirects are allowed.
- `same-origin`: Redirects are **allowed if the redirect URL is the same origin** (as the URL given to `open()`).
- `true`: **All** redirects are allowed. **Not recommended.**

**Comment by CanadaHonk** [comment]
Done in new `allowNavigation` option, to be released on 0.13

**Comment by iacore** [comment]
This is not working for me for some reason. I use Librewolf.

Download project here: https://github.com/iacore/solid-gluon-thingy/releases/tag/bug-navigate

https://github.com/gluon-framework/gluon/assets/74560659/f9ab1993-581a-4879-9f86-2dac6fbac3c2


https://github.com/gluon-framework/gluon/assets/74560659/28245f5d-fcbd-43dd-ab42-4025f4bfc44b
