### ISSUE TITLE
Thorium as a recommended gluon brower-base

### ISSUE THREAD

**Issue by couleurm** [gluon-framework/gluon#61]
Some of us gluon enjoyers want less RAM but we can't live in a perfect tauri world, gluon is the least worst alternative from avoiding JavaScript completely.

Some of us want performance, so why not recommend using [Thorium](https://thorium.rocks) since it's a fast browser (not as secure as hardened firefox but, it's not like you're gonna browse the web with a gluon app, are you 🤣?)

**Comment by CanadaHonk** [comment]
Gluon already supports Thorium, and we won't recommend a browser base as we don't want to induce bias and it should use what the user has installed already. Developer and user choice is important :)

**Comment by couleurm** [comment]
I accept that, what is your choice as Gluon's developper?

**Comment by CanadaHonk** [comment]
I don't have a choice as developers should not particularly choose, Gluon will use any compatible browser installed.

**Comment by couleurm** [comment]
Okay let me ask this straighter: if you were a power user what would you use for best performance and/or privacy?

**Comment by CanadaHonk** [comment]
Depending on if you prefer Chromium or Firefox, Thorium or LibreWolf probably for power users, but I mostly just use Chromium.

(Also Tauri does not really use less memory. That's mostly a myth.)
