### ISSUE TITLE
IPC will not be available after page refresh

### ISSUE THREAD

**Issue by callmeyan** [gluon-framework/gluon#63]
use code like 
```
// backend
const win = await Gluon.open('index.html', {
    windowSize: [800, 500]
  });
win.ipc.test= async (data) => {
    //....
})
// frontend
await Gluon.ipc.test('Message!');
```
 invoke success on first run but after refresh page invoke will got error `Uncaught (in promise) TypeError: Gluon.ipc.test is not a function`

**Comment by CanadaHonk** [comment]
This is fixed already in 0.14.0 (install from GitHub to use alpha or wait a few days for release).
